#!/bin/sh

expect -c '
set timeout -1;
spawn /taulabs/tools/android-sdk-linux/tools/android update sdk --no-ui -t build-tools-19.1.0,android-14,platform-tools,tools;
expect {
    "Do you accept the license" { exp_send "y\r" ; exp_continue }
    eof
}
'
